### ISSUE TITLE
v10.8.10

### ISSUE THREAD

**Issue by aleksasiriski** [ConfusedPolarBear/intro-skipper#156]
Please update to v10.8.10

**Comment by roib20** [comment]
My current PR #157 addresses [GHSA-9p5f-5x8v-x65m](https://github.com/jellyfin/jellyfin/security/advisories/GHSA-9p5f-5x8v-x65m) in jellyfin/jellyfin. However the [web interface fork for intro-skipper](https://github.com/ConfusedPolarBear/jellyfin-web/tree/intros) also needs to be updated to 10.8.10, in order to close [GHSA-89hp-h43h-r5pq](https://github.com/jellyfin/jellyfin-web/security/advisories/GHSA-89hp-h43h-r5pq) in jellyfin/jellyfin-web.

**Comment by AlexanderBabel** [comment]
In the mean time, I can offer you guys a custom docker image, that builds the vanilla jellyfin-web repo and applies the intro changes through a patch that is dynamically obtained.

The image is hosted at `alexbabel/jellyfin:10.8.10-1-ls209` and `ghcr.io/alexanderbabel/jellyfin:10.8.10-1-ls209`.

The source is documented [here](https://github.com/AlexanderBabel/custom-images/blob/main/jellyfin/Dockerfile). The image uses linuxserver's image as the base.

**Comment by aleksasiriski** [comment]
I have the official (not ls.io) image at `ghcr.io/aleksasiriski/jellyfin-rffmpeg-intro-skipper`, will add autobuilding of web interface later today.

**Comment by roib20** [comment]
Alright I just saw the @ConfusedPolarBear made all the necessary changes today to fully update jellyfin-intro-skipper to v10.8.10 – including the container image and web UI.

The relevant commits are:
+ ConfusedPolarBear/intro-skipper commit [`49cd1a4`](https://github.com/ConfusedPolarBear/intro-skipper/commit/49cd1a49a0d99ab4d7948eb1b5f100468d8aad85)
+ ConfusedPolarBear/intro-skipper commit [`78afae4`](https://github.com/ConfusedPolarBear/intro-skipper/commit/78afae40b6d6dbd40c3e6a6454eb2bd0ecd3d164)
+ ConfusedPolarBear/jellyfin-web commit [`4d9c94b`](https://github.com/ConfusedPolarBear/jellyfin-web/commit/4d9c94b8f109435b68ea864bcea3bc41dfceb128)

Users can now update jellyfin-intro-skipper container image to the following tag: [`ghcr.io/confusedpolarbear/jellyfin-intro-skipper:10.8.10`](https://github.com/ConfusedPolarBear/intro-skipper/pkgs/container/jellyfin-intro-skipper/88081812?tag=10.8.10). The [`latest`](https://github.com/ConfusedPolarBear/intro-skipper/pkgs/container/jellyfin-intro-skipper/88081812?tag=latest) tag also currently points to `10.8.10`.

My understanding is this issue is now solved and can be closed.
